name: inception
services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    networks:
      - netception
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - netception
    restart: unless-stopped
    healthcheck:
      test: "mariadb ${MARIADB_DATABASE} -u${MARIADB_USER} -p${MARIADB_PASSWORD} -e 'SELECT 1;'"
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 3      
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      USER_LOGIN: ${USER_LOGIN}
      USER_EMAIL: ${USER_EMAIL}
    networks:
      - netception
volumes:
  mariadb_data: {}
  wp_data: {}
networks:
  netception:
