name: inception
services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    networks:
      - netception
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - netception
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -p$MARIADB_ROOT_PASSWORD || exit 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20      
    # env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - netception
volumes:
  mariadb_data: {}
  wp_data: {}
networks:
  netception:
